--
-- PostgreSQL database dump
--

\restrict oBGcvjmbcHTbIveQttcIxl7iSggP7hBY5OkAUpSc2F678bH1zMlOoxFimrHc3gA

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO iolta_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO iolta_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO iolta_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO iolta_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO iolta_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO iolta_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_accounts; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.bank_accounts (
    id bigint NOT NULL,
    account_number character varying(50) NOT NULL,
    bank_name character varying(200) NOT NULL,
    bank_address text,
    account_name character varying(200) NOT NULL,
    routing_number character varying(20),
    account_type character varying(50) NOT NULL,
    opening_balance numeric(15,2) NOT NULL,
    next_check_number integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.bank_accounts OWNER TO iolta_user;

--
-- Name: bank_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.bank_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_reconciliations; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.bank_reconciliations (
    id bigint NOT NULL,
    reconciliation_date date NOT NULL,
    statement_balance numeric(15,2) NOT NULL,
    book_balance numeric(15,2) NOT NULL,
    is_reconciled boolean NOT NULL,
    reconciled_by character varying(100),
    reconciled_at timestamp with time zone,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    bank_account_id bigint NOT NULL
);


ALTER TABLE public.bank_reconciliations OWNER TO iolta_user;

--
-- Name: bank_reconciliations_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.bank_reconciliations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_reconciliations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_transaction_audit; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.bank_transaction_audit (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    action_date timestamp with time zone NOT NULL,
    action_by character varying(100) NOT NULL,
    old_values jsonb,
    new_values jsonb,
    old_amount numeric(15,2),
    new_amount numeric(15,2),
    old_status character varying(20),
    new_status character varying(20),
    change_reason text NOT NULL,
    ip_address inet,
    transaction_id bigint NOT NULL
);


ALTER TABLE public.bank_transaction_audit OWNER TO iolta_user;

--
-- Name: bank_transaction_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.bank_transaction_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_transaction_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_transactions; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.bank_transactions (
    id bigint NOT NULL,
    transaction_number character varying(100),
    transaction_date date NOT NULL,
    transaction_type character varying(20) NOT NULL,
    amount numeric(15,2) NOT NULL,
    description text NOT NULL,
    check_memo character varying(500) NOT NULL,
    reference_number character varying(100),
    payee character varying(255) NOT NULL,
    item_type character varying(20) NOT NULL,
    cleared_date date,
    check_is_printed boolean NOT NULL,
    voided_date timestamp with time zone,
    voided_by character varying(100) NOT NULL,
    void_reason text NOT NULL,
    post_date date,
    bank_reference character varying(100) NOT NULL,
    bank_category character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    reconciliation_notes text NOT NULL,
    rec_id integer,
    data_source character varying(20) NOT NULL,
    import_batch_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(100) NOT NULL,
    original_transaction_id integer,
    original_item_id integer,
    bank_account_id bigint NOT NULL,
    case_id bigint,
    client_id bigint,
    vendor_id bigint
);


ALTER TABLE public.bank_transactions OWNER TO iolta_user;

--
-- Name: bank_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.bank_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: case_number_counter; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.case_number_counter (
    id bigint NOT NULL,
    last_number integer NOT NULL
);


ALTER TABLE public.case_number_counter OWNER TO iolta_user;

--
-- Name: case_number_counter_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.case_number_counter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.case_number_counter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cases; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.cases (
    id bigint NOT NULL,
    case_number character varying(100) NOT NULL,
    case_title character varying(255) NOT NULL,
    case_description text,
    case_amount numeric(15,2),
    case_status character varying(50) NOT NULL,
    opened_date date,
    closed_date date,
    is_active boolean NOT NULL,
    data_source character varying(20) NOT NULL,
    import_batch_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL
);


ALTER TABLE public.cases OWNER TO iolta_user;

--
-- Name: cases_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.cases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: check_sequences; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.check_sequences (
    id bigint NOT NULL,
    next_check_number integer NOT NULL,
    last_assigned_number integer,
    last_assigned_date timestamp with time zone,
    bank_account_id bigint NOT NULL
);


ALTER TABLE public.check_sequences OWNER TO iolta_user;

--
-- Name: check_sequences_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.check_sequences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.check_sequences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    client_number character varying(50),
    client_name character varying(200) NOT NULL,
    email character varying(254),
    phone character varying(20),
    address text,
    city character varying(100),
    state character varying(2),
    zip_code character varying(20),
    trust_account_status character varying(30) NOT NULL,
    is_active boolean NOT NULL,
    data_source character varying(20) NOT NULL,
    import_batch_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.clients OWNER TO iolta_user;

--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO iolta_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO iolta_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO iolta_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO iolta_user;

--
-- Name: import_audit; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.import_audit (
    id bigint NOT NULL,
    import_date timestamp with time zone NOT NULL,
    import_type character varying(20) NOT NULL,
    file_name character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    total_records integer NOT NULL,
    successful_records integer NOT NULL,
    failed_records integer NOT NULL,
    clients_created integer NOT NULL,
    cases_created integer NOT NULL,
    transactions_created integer NOT NULL,
    vendors_created integer NOT NULL,
    clients_skipped integer NOT NULL,
    cases_skipped integer NOT NULL,
    vendors_skipped integer NOT NULL,
    rows_with_errors integer NOT NULL,
    expected_clients integer NOT NULL,
    expected_cases integer NOT NULL,
    expected_transactions integer NOT NULL,
    expected_vendors integer NOT NULL,
    total_clients_in_csv integer NOT NULL,
    total_cases_in_csv integer NOT NULL,
    total_transactions_in_csv integer NOT NULL,
    total_vendors_in_csv integer NOT NULL,
    existing_clients integer NOT NULL,
    existing_cases integer NOT NULL,
    existing_vendors integer NOT NULL,
    preview_data text NOT NULL,
    preview_errors text NOT NULL,
    error_log text NOT NULL,
    imported_by character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone
);


ALTER TABLE public.import_audit OWNER TO iolta_user;

--
-- Name: import_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.import_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_logs; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.import_logs (
    id bigint NOT NULL,
    import_type character varying(50) NOT NULL,
    filename character varying(255),
    status character varying(20) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    total_rows integer,
    clients_created integer DEFAULT 0 NOT NULL,
    clients_existing integer DEFAULT 0 NOT NULL,
    cases_created integer DEFAULT 0 NOT NULL,
    transactions_created integer DEFAULT 0 NOT NULL,
    transactions_skipped integer DEFAULT 0 NOT NULL,
    errors jsonb,
    summary jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer
);


ALTER TABLE public.import_logs OWNER TO iolta_user;

--
-- Name: import_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.import_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: law_firm; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.law_firm (
    id bigint NOT NULL,
    firm_name character varying(200) NOT NULL,
    doing_business_as character varying(200) NOT NULL,
    address_line1 character varying(100) NOT NULL,
    address_line2 character varying(100) NOT NULL,
    city character varying(50) NOT NULL,
    state character varying(2) NOT NULL,
    zip_code character varying(10) NOT NULL,
    phone character varying(20) NOT NULL,
    fax character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    website character varying(200) NOT NULL,
    principal_attorney character varying(100) NOT NULL,
    attorney_bar_number character varying(20) NOT NULL,
    attorney_state character varying(2) NOT NULL,
    trust_account_required boolean NOT NULL,
    iolta_compliant boolean NOT NULL,
    trust_account_certification_date date,
    tax_id character varying(20) NOT NULL,
    state_registration character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    approval_threshold numeric(10,2) DEFAULT 10000.00 NOT NULL
);


ALTER TABLE public.law_firm OWNER TO iolta_user;

--
-- Name: law_firm_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.law_firm ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.law_firm_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.settings (
    id bigint NOT NULL,
    category character varying(50) NOT NULL,
    key character varying(100) NOT NULL,
    value character varying(255) NOT NULL,
    display_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.settings OWNER TO iolta_user;

--
-- Name: settings_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlement_distributions; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.settlement_distributions (
    id bigint NOT NULL,
    distribution_type character varying(20) NOT NULL,
    amount numeric(15,2) NOT NULL,
    description text,
    check_number character varying(50),
    is_paid boolean NOT NULL,
    paid_date date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint,
    settlement_id bigint NOT NULL,
    vendor_id bigint
);


ALTER TABLE public.settlement_distributions OWNER TO iolta_user;

--
-- Name: settlement_distributions_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.settlement_distributions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_distributions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlement_reconciliations; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.settlement_reconciliations (
    id bigint NOT NULL,
    bank_balance_before numeric(15,2) NOT NULL,
    bank_balance_after numeric(15,2) NOT NULL,
    client_balance_before numeric(15,2) NOT NULL,
    client_balance_after numeric(15,2) NOT NULL,
    total_distributions numeric(15,2) NOT NULL,
    reconciliation_status character varying(20) NOT NULL,
    reconciled_by character varying(100),
    reconciled_at timestamp with time zone,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    settlement_id bigint NOT NULL
);


ALTER TABLE public.settlement_reconciliations OWNER TO iolta_user;

--
-- Name: settlement_reconciliations_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.settlement_reconciliations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_reconciliations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlements; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.settlements (
    id bigint NOT NULL,
    settlement_number character varying(100),
    settlement_date date NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    status character varying(20) NOT NULL,
    notes text,
    created_by character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    bank_account_id bigint NOT NULL,
    case_id bigint,
    client_id bigint NOT NULL
);


ALTER TABLE public.settlements OWNER TO iolta_user;

--
-- Name: settlements_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_approvals; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.transaction_approvals (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    reviewed_at timestamp with time zone,
    status character varying(20) NOT NULL,
    request_notes text NOT NULL,
    review_notes text NOT NULL,
    ip_address inet,
    created_by_id integer NOT NULL,
    reviewed_by_id integer,
    transaction_id bigint NOT NULL,
    CONSTRAINT prevent_self_approval CHECK (((reviewed_by_id IS NULL) OR (NOT ((created_by_id = reviewed_by_id) AND (reviewed_by_id IS NOT NULL)))))
);


ALTER TABLE public.transaction_approvals OWNER TO iolta_user;

--
-- Name: transaction_approvals_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.transaction_approvals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_approvals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.user_profiles (
    id bigint NOT NULL,
    role character varying(30) NOT NULL,
    phone character varying(20) NOT NULL,
    employee_id character varying(50) NOT NULL,
    department character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    can_approve_transactions boolean NOT NULL,
    can_reconcile boolean NOT NULL,
    can_print_checks boolean NOT NULL,
    can_manage_users boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer,
    user_id integer NOT NULL
);


ALTER TABLE public.user_profiles OWNER TO iolta_user;

--
-- Name: user_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.user_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendor_types; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.vendor_types (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL,
    data_source character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.vendor_types OWNER TO iolta_user;

--
-- Name: vendor_types_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.vendor_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendors; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.vendors (
    id bigint NOT NULL,
    vendor_number character varying(50),
    vendor_name character varying(200) NOT NULL,
    contact_person character varying(200),
    email character varying(254),
    phone character varying(20),
    address text,
    city character varying(100),
    state character varying(2),
    zip_code character varying(20),
    tax_id character varying(50),
    is_active boolean NOT NULL,
    data_source character varying(20) NOT NULL,
    import_batch_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint,
    vendor_type_id bigint
);


ALTER TABLE public.vendors OWNER TO iolta_user;

--
-- Name: vendors_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.vendors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: bank_accounts bank_accounts_account_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_accounts
    ADD CONSTRAINT bank_accounts_account_number_key UNIQUE (account_number);


--
-- Name: bank_accounts bank_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_accounts
    ADD CONSTRAINT bank_accounts_pkey PRIMARY KEY (id);


--
-- Name: bank_reconciliations bank_reconciliations_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_reconciliations
    ADD CONSTRAINT bank_reconciliations_pkey PRIMARY KEY (id);


--
-- Name: bank_transaction_audit bank_transaction_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transaction_audit
    ADD CONSTRAINT bank_transaction_audit_pkey PRIMARY KEY (id);


--
-- Name: bank_transactions bank_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_pkey PRIMARY KEY (id);


--
-- Name: bank_transactions bank_transactions_transaction_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_transaction_number_key UNIQUE (transaction_number);


--
-- Name: case_number_counter case_number_counter_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.case_number_counter
    ADD CONSTRAINT case_number_counter_pkey PRIMARY KEY (id);


--
-- Name: cases cases_case_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.cases
    ADD CONSTRAINT cases_case_number_key UNIQUE (case_number);


--
-- Name: cases cases_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.cases
    ADD CONSTRAINT cases_pkey PRIMARY KEY (id);


--
-- Name: check_sequences check_sequences_bank_account_id_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.check_sequences
    ADD CONSTRAINT check_sequences_bank_account_id_key UNIQUE (bank_account_id);


--
-- Name: check_sequences check_sequences_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.check_sequences
    ADD CONSTRAINT check_sequences_pkey PRIMARY KEY (id);


--
-- Name: clients clients_client_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_client_number_key UNIQUE (client_number);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: import_audit import_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.import_audit
    ADD CONSTRAINT import_audit_pkey PRIMARY KEY (id);


--
-- Name: import_logs import_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.import_logs
    ADD CONSTRAINT import_logs_pkey PRIMARY KEY (id);


--
-- Name: law_firm law_firm_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.law_firm
    ADD CONSTRAINT law_firm_pkey PRIMARY KEY (id);


--
-- Name: settings settings_category_key_db3f85ba_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_category_key_db3f85ba_uniq UNIQUE (category, key);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (id);


--
-- Name: settlement_distributions settlement_distributions_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_distributions
    ADD CONSTRAINT settlement_distributions_pkey PRIMARY KEY (id);


--
-- Name: settlement_reconciliations settlement_reconciliations_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_reconciliations
    ADD CONSTRAINT settlement_reconciliations_pkey PRIMARY KEY (id);


--
-- Name: settlement_reconciliations settlement_reconciliations_settlement_id_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_reconciliations
    ADD CONSTRAINT settlement_reconciliations_settlement_id_key UNIQUE (settlement_id);


--
-- Name: settlements settlements_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_pkey PRIMARY KEY (id);


--
-- Name: settlements settlements_settlement_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_settlement_number_key UNIQUE (settlement_number);


--
-- Name: transaction_approvals transaction_approvals_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.transaction_approvals
    ADD CONSTRAINT transaction_approvals_pkey PRIMARY KEY (id);


--
-- Name: transaction_approvals transaction_approvals_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.transaction_approvals
    ADD CONSTRAINT transaction_approvals_transaction_id_key UNIQUE (transaction_id);


--
-- Name: clients unique_client_name; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT unique_client_name UNIQUE (client_name);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);


--
-- Name: user_profiles user_profiles_user_id_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_key UNIQUE (user_id);


--
-- Name: vendor_types vendor_types_name_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendor_types
    ADD CONSTRAINT vendor_types_name_key UNIQUE (name);


--
-- Name: vendor_types vendor_types_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendor_types
    ADD CONSTRAINT vendor_types_pkey PRIMARY KEY (id);


--
-- Name: vendors vendors_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_pkey PRIMARY KEY (id);


--
-- Name: vendors vendors_vendor_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_vendor_number_key UNIQUE (vendor_number);


--
-- Name: audit_action_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX audit_action_idx ON public.bank_transaction_audit USING btree (action);


--
-- Name: audit_date_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX audit_date_idx ON public.bank_transaction_audit USING btree (action_date);


--
-- Name: audit_trans_date_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX audit_trans_date_idx ON public.bank_transaction_audit USING btree (transaction_id, action_date DESC);


--
-- Name: audit_user_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX audit_user_idx ON public.bank_transaction_audit USING btree (action_by);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: bank_accounts_account_number_c5d2f925_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_accounts_account_number_c5d2f925_like ON public.bank_accounts USING btree (account_number varchar_pattern_ops);


--
-- Name: bank_reconciliations_bank_account_id_c56ef498; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_reconciliations_bank_account_id_c56ef498 ON public.bank_reconciliations USING btree (bank_account_id);


--
-- Name: bank_transa_bank_ac_89ae9f_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_bank_ac_89ae9f_idx ON public.bank_transactions USING btree (bank_account_id, transaction_date);


--
-- Name: bank_transa_case_id_7c7fc6_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_case_id_7c7fc6_idx ON public.bank_transactions USING btree (case_id);


--
-- Name: bank_transa_client__d9d9d7_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_client__d9d9d7_idx ON public.bank_transactions USING btree (client_id);


--
-- Name: bank_transa_referen_cb533e_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_referen_cb533e_idx ON public.bank_transactions USING btree (reference_number);


--
-- Name: bank_transa_status_a92de8_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_status_a92de8_idx ON public.bank_transactions USING btree (status, transaction_date);


--
-- Name: bank_transa_status_b8b399_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_status_b8b399_idx ON public.bank_transactions USING btree (status);


--
-- Name: bank_transa_transac_a4828a_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_transac_a4828a_idx ON public.bank_transactions USING btree (transaction_number);


--
-- Name: bank_transa_transac_a87669_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_transac_a87669_idx ON public.bank_transactions USING btree (transaction_date, transaction_type);


--
-- Name: bank_transa_vendor__92455e_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_vendor__92455e_idx ON public.bank_transactions USING btree (vendor_id);


--
-- Name: bank_transaction_audit_transaction_id_8fd3002a; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transaction_audit_transaction_id_8fd3002a ON public.bank_transaction_audit USING btree (transaction_id);


--
-- Name: bank_transactions_bank_account_id_66f7cc01; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transactions_bank_account_id_66f7cc01 ON public.bank_transactions USING btree (bank_account_id);


--
-- Name: bank_transactions_case_id_6affebb3; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transactions_case_id_6affebb3 ON public.bank_transactions USING btree (case_id);


--
-- Name: bank_transactions_client_id_405c5e3b; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transactions_client_id_405c5e3b ON public.bank_transactions USING btree (client_id);


--
-- Name: bank_transactions_transaction_number_b51b6526_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transactions_transaction_number_b51b6526_like ON public.bank_transactions USING btree (transaction_number varchar_pattern_ops);


--
-- Name: bank_transactions_vendor_id_da6a5c0d; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transactions_vendor_id_da6a5c0d ON public.bank_transactions USING btree (vendor_id);


--
-- Name: cases_case_number_a80b753e_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX cases_case_number_a80b753e_like ON public.cases USING btree (case_number varchar_pattern_ops);


--
-- Name: cases_client_id_fcf3eac3; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX cases_client_id_fcf3eac3 ON public.cases USING btree (client_id);


--
-- Name: clients_client_number_0055cce2_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX clients_client_number_0055cce2_like ON public.clients USING btree (client_number varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: import_logs_created_by_id_5a65dd9a; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX import_logs_created_by_id_5a65dd9a ON public.import_logs USING btree (created_by_id);


--
-- Name: settlement_distributions_client_id_23cf5585; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlement_distributions_client_id_23cf5585 ON public.settlement_distributions USING btree (client_id);


--
-- Name: settlement_distributions_settlement_id_204f0ace; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlement_distributions_settlement_id_204f0ace ON public.settlement_distributions USING btree (settlement_id);


--
-- Name: settlement_distributions_vendor_id_dbb05069; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlement_distributions_vendor_id_dbb05069 ON public.settlement_distributions USING btree (vendor_id);


--
-- Name: settlements_bank_account_id_10bf7939; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlements_bank_account_id_10bf7939 ON public.settlements USING btree (bank_account_id);


--
-- Name: settlements_case_id_5616be20; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlements_case_id_5616be20 ON public.settlements USING btree (case_id);


--
-- Name: settlements_client_id_58af542e; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlements_client_id_58af542e ON public.settlements USING btree (client_id);


--
-- Name: settlements_settlement_number_2b9b9f04_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlements_settlement_number_2b9b9f04_like ON public.settlements USING btree (settlement_number varchar_pattern_ops);


--
-- Name: transaction_approvals_created_by_id_64b6d531; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_approvals_created_by_id_64b6d531 ON public.transaction_approvals USING btree (created_by_id);


--
-- Name: transaction_approvals_reviewed_by_id_e9cd8251; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_approvals_reviewed_by_id_e9cd8251 ON public.transaction_approvals USING btree (reviewed_by_id);


--
-- Name: transaction_approvals_status_7cf81d68; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_approvals_status_7cf81d68 ON public.transaction_approvals USING btree (status);


--
-- Name: transaction_approvals_status_7cf81d68_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_approvals_status_7cf81d68_like ON public.transaction_approvals USING btree (status varchar_pattern_ops);


--
-- Name: transaction_created_08a22b_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_created_08a22b_idx ON public.transaction_approvals USING btree (created_by_id, status);


--
-- Name: transaction_reviewe_12700f_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_reviewe_12700f_idx ON public.transaction_approvals USING btree (reviewed_by_id, status);


--
-- Name: transaction_status_d64ec1_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_status_d64ec1_idx ON public.transaction_approvals USING btree (status, created_at DESC);


--
-- Name: user_profiles_created_by_id_e23d6f71; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX user_profiles_created_by_id_e23d6f71 ON public.user_profiles USING btree (created_by_id);


--
-- Name: vendor_types_name_a158871a_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX vendor_types_name_a158871a_like ON public.vendor_types USING btree (name varchar_pattern_ops);


--
-- Name: vendors_client_id_9964fb3b; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX vendors_client_id_9964fb3b ON public.vendors USING btree (client_id);


--
-- Name: vendors_vendor_number_f40f56ef_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX vendors_vendor_number_f40f56ef_like ON public.vendors USING btree (vendor_number varchar_pattern_ops);


--
-- Name: vendors_vendor_type_id_aa46b9df; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX vendors_vendor_type_id_aa46b9df ON public.vendors USING btree (vendor_type_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_reconciliations bank_reconciliations_bank_account_id_c56ef498_fk_bank_acco; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_reconciliations
    ADD CONSTRAINT bank_reconciliations_bank_account_id_c56ef498_fk_bank_acco FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_transaction_audit bank_transaction_aud_transaction_id_8fd3002a_fk_bank_tran; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transaction_audit
    ADD CONSTRAINT bank_transaction_aud_transaction_id_8fd3002a_fk_bank_tran FOREIGN KEY (transaction_id) REFERENCES public.bank_transactions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_transactions bank_transactions_bank_account_id_66f7cc01_fk_bank_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_bank_account_id_66f7cc01_fk_bank_accounts_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_transactions bank_transactions_case_id_6affebb3_fk_cases_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_case_id_6affebb3_fk_cases_id FOREIGN KEY (case_id) REFERENCES public.cases(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_transactions bank_transactions_client_id_405c5e3b_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_client_id_405c5e3b_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_transactions bank_transactions_vendor_id_da6a5c0d_fk_vendors_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_vendor_id_da6a5c0d_fk_vendors_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cases cases_client_id_fcf3eac3_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.cases
    ADD CONSTRAINT cases_client_id_fcf3eac3_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: check_sequences check_sequences_bank_account_id_7ade4d4f_fk_bank_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.check_sequences
    ADD CONSTRAINT check_sequences_bank_account_id_7ade4d4f_fk_bank_accounts_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: import_logs import_logs_created_by_id_5a65dd9a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.import_logs
    ADD CONSTRAINT import_logs_created_by_id_5a65dd9a_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlement_distributions settlement_distribut_settlement_id_204f0ace_fk_settlemen; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_distributions
    ADD CONSTRAINT settlement_distribut_settlement_id_204f0ace_fk_settlemen FOREIGN KEY (settlement_id) REFERENCES public.settlements(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlement_distributions settlement_distributions_client_id_23cf5585_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_distributions
    ADD CONSTRAINT settlement_distributions_client_id_23cf5585_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlement_distributions settlement_distributions_vendor_id_dbb05069_fk_vendors_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_distributions
    ADD CONSTRAINT settlement_distributions_vendor_id_dbb05069_fk_vendors_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlement_reconciliations settlement_reconcili_settlement_id_072637c7_fk_settlemen; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_reconciliations
    ADD CONSTRAINT settlement_reconcili_settlement_id_072637c7_fk_settlemen FOREIGN KEY (settlement_id) REFERENCES public.settlements(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlements settlements_bank_account_id_10bf7939_fk_bank_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_bank_account_id_10bf7939_fk_bank_accounts_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlements settlements_case_id_5616be20_fk_cases_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_case_id_5616be20_fk_cases_id FOREIGN KEY (case_id) REFERENCES public.cases(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlements settlements_client_id_58af542e_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_client_id_58af542e_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaction_approvals transaction_approval_transaction_id_091f992e_fk_bank_tran; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.transaction_approvals
    ADD CONSTRAINT transaction_approval_transaction_id_091f992e_fk_bank_tran FOREIGN KEY (transaction_id) REFERENCES public.bank_transactions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaction_approvals transaction_approvals_created_by_id_64b6d531_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.transaction_approvals
    ADD CONSTRAINT transaction_approvals_created_by_id_64b6d531_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaction_approvals transaction_approvals_reviewed_by_id_e9cd8251_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.transaction_approvals
    ADD CONSTRAINT transaction_approvals_reviewed_by_id_e9cd8251_fk_auth_user_id FOREIGN KEY (reviewed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_profiles user_profiles_created_by_id_e23d6f71_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_created_by_id_e23d6f71_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_profiles user_profiles_user_id_8c5ab5fe_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_8c5ab5fe_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vendors vendors_client_id_9964fb3b_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_client_id_9964fb3b_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vendors vendors_vendor_type_id_aa46b9df_fk_vendor_types_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_vendor_type_id_aa46b9df_fk_vendor_types_id FOREIGN KEY (vendor_type_id) REFERENCES public.vendor_types(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict oBGcvjmbcHTbIveQttcIxl7iSggP7hBY5OkAUpSc2F678bH1zMlOoxFimrHc3gA


-- ============================================
-- SEED DATA: Law Firm Configuration
-- ============================================

INSERT INTO public.law_firm (
    id, firm_name, doing_business_as, address_line1, address_line2, 
    city, state, zip_code, phone, fax, email, website,
    principal_attorney, attorney_bar_number, attorney_state,
    trust_account_required, iolta_compliant, trust_account_certification_date,
    tax_id, state_registration, is_active, created_at, updated_at, approval_threshold
) VALUES (
    1, 
    'Sample Law Firm PLLC',
    NULL,
    '123 Legal Street',
    'Suite 100',
    'New York',
    'NY',
    '10001',
    '(555) 123-4567',
    '(555) 123-4568',
    'contact@samplelawfirm.com',
    'https://www.samplelawfirm.com',
    'John Smith, Esq.',
    '123456',
    'NY',
    true,
    true,
    '2025-01-01',
    '12-3456789',
    'NY-REG-001',
    true,
    NOW(),
    NOW(),
    10000.00
);

SELECT setval('public.law_firm_id_seq', 1, true);

-- ============================================
-- SEED DATA: Bank Account (IOLTA Trust Account)
-- ============================================

INSERT INTO public.bank_accounts (
    id, account_number, bank_name, bank_address, account_name, 
    routing_number, account_type, opening_balance, next_check_number, 
    is_active, created_at, updated_at
) VALUES (
    1,
    '1234567890',
    'Chase Bank',
    '270 Park Avenue, New York, NY 10017',
    'IOLTA Trust Account',
    '021000021',
    'Trust Account',
    0.00,
    1001,
    true,
    NOW(),
    NOW()
);

SELECT setval('public.bank_accounts_id_seq', 1, true);

-- ============================================
-- SEED DATA: Check Sequence
-- ============================================

INSERT INTO public.check_sequences (
    id, next_check_number, last_assigned_number, last_assigned_date, bank_account_id
) VALUES (
    1,
    1001,
    NULL,
    NULL,
    1
);

SELECT setval('public.check_sequences_id_seq', 1, true);

-- ============================================
-- END OF SEED DATA
-- ============================================
