--
-- PostgreSQL database dump
--

\restrict MFn0vEyxGEB8peGuKhFi4fDzrgNx0ZAW3VMQpOd4eACXiFWXwV8ppnwmvl6eMWx

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS iolta_guard_db;
--
-- Name: iolta_guard_db; Type: DATABASE; Schema: -; Owner: iolta_user
--

CREATE DATABASE iolta_guard_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE iolta_guard_db OWNER TO iolta_user;

\unrestrict MFn0vEyxGEB8peGuKhFi4fDzrgNx0ZAW3VMQpOd4eACXiFWXwV8ppnwmvl6eMWx
\connect iolta_guard_db
\restrict MFn0vEyxGEB8peGuKhFi4fDzrgNx0ZAW3VMQpOd4eACXiFWXwV8ppnwmvl6eMWx

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: iolta_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO iolta_user;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: iolta_user
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO iolta_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO iolta_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO iolta_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO iolta_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO iolta_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO iolta_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_accounts; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.bank_accounts (
    id bigint NOT NULL,
    account_number character varying(50) NOT NULL,
    bank_name character varying(200) NOT NULL,
    bank_address text,
    account_name character varying(200) NOT NULL,
    routing_number character varying(20),
    account_type character varying(50) NOT NULL,
    opening_balance numeric(15,2) NOT NULL,
    next_check_number integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.bank_accounts OWNER TO iolta_user;

--
-- Name: bank_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.bank_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_reconciliations; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.bank_reconciliations (
    id bigint NOT NULL,
    reconciliation_date date NOT NULL,
    statement_balance numeric(15,2) NOT NULL,
    book_balance numeric(15,2) NOT NULL,
    is_reconciled boolean NOT NULL,
    reconciled_by character varying(100),
    reconciled_at timestamp with time zone,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    bank_account_id bigint NOT NULL
);


ALTER TABLE public.bank_reconciliations OWNER TO iolta_user;

--
-- Name: bank_reconciliations_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.bank_reconciliations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_reconciliations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_transaction_audit; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.bank_transaction_audit (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    action_date timestamp with time zone NOT NULL,
    action_by character varying(100) NOT NULL,
    old_values jsonb,
    new_values jsonb,
    old_amount numeric(15,2),
    new_amount numeric(15,2),
    old_status character varying(20),
    new_status character varying(20),
    change_reason text NOT NULL,
    ip_address inet,
    transaction_id bigint NOT NULL
);


ALTER TABLE public.bank_transaction_audit OWNER TO iolta_user;

--
-- Name: bank_transaction_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.bank_transaction_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_transaction_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bank_transactions; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.bank_transactions (
    id bigint NOT NULL,
    transaction_number character varying(100),
    transaction_date date NOT NULL,
    transaction_type character varying(20) NOT NULL,
    amount numeric(15,2) NOT NULL,
    description text NOT NULL,
    check_memo character varying(500) NOT NULL,
    reference_number character varying(100) NOT NULL,
    payee character varying(255) NOT NULL,
    item_type character varying(20) NOT NULL,
    cleared_date date,
    check_is_printed boolean NOT NULL,
    voided_date timestamp with time zone,
    voided_by character varying(100) NOT NULL,
    void_reason text NOT NULL,
    post_date date,
    bank_reference character varying(100) NOT NULL,
    bank_category character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    reconciliation_notes text NOT NULL,
    rec_id integer,
    data_source character varying(20) NOT NULL,
    import_batch_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by character varying(100) NOT NULL,
    original_transaction_id integer,
    original_item_id integer,
    bank_account_id bigint NOT NULL,
    case_id bigint,
    client_id bigint,
    vendor_id bigint NOT NULL,
    check_number character varying(50)
);


ALTER TABLE public.bank_transactions OWNER TO iolta_user;

--
-- Name: bank_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.bank_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: case_number_counter; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.case_number_counter (
    id bigint NOT NULL,
    last_number integer NOT NULL
);


ALTER TABLE public.case_number_counter OWNER TO iolta_user;

--
-- Name: case_number_counter_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.case_number_counter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.case_number_counter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cases; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.cases (
    id bigint NOT NULL,
    case_number character varying(100) NOT NULL,
    case_title character varying(255) NOT NULL,
    case_description text,
    case_amount numeric(15,2),
    case_status character varying(50) NOT NULL,
    opened_date date,
    closed_date date,
    is_active boolean NOT NULL,
    data_source character varying(20) NOT NULL,
    import_batch_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL
);


ALTER TABLE public.cases OWNER TO iolta_user;

--
-- Name: cases_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.cases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: check_sequences; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.check_sequences (
    id bigint NOT NULL,
    next_check_number integer NOT NULL,
    last_assigned_number integer,
    last_assigned_date timestamp with time zone,
    bank_account_id bigint NOT NULL
);


ALTER TABLE public.check_sequences OWNER TO iolta_user;

--
-- Name: check_sequences_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.check_sequences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.check_sequences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    client_number character varying(50),
    client_name character varying(200) NOT NULL,
    email character varying(254),
    phone character varying(20),
    address text,
    city character varying(100),
    state character varying(2),
    zip_code character varying(20),
    trust_account_status character varying(30) NOT NULL,
    is_active boolean NOT NULL,
    data_source character varying(20) NOT NULL,
    import_batch_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.clients OWNER TO iolta_user;

--
-- Name: clients_assigned_users; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.clients_assigned_users (
    id bigint NOT NULL,
    client_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.clients_assigned_users OWNER TO iolta_user;

--
-- Name: clients_assigned_users_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.clients_assigned_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_assigned_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO iolta_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO iolta_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO iolta_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO iolta_user;

--
-- Name: import_audit; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.import_audit (
    id bigint NOT NULL,
    import_date timestamp with time zone NOT NULL,
    import_type character varying(20) NOT NULL,
    file_name character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    total_records integer NOT NULL,
    successful_records integer NOT NULL,
    failed_records integer NOT NULL,
    clients_created integer NOT NULL,
    cases_created integer NOT NULL,
    transactions_created integer NOT NULL,
    vendors_created integer NOT NULL,
    clients_skipped integer NOT NULL,
    cases_skipped integer NOT NULL,
    vendors_skipped integer NOT NULL,
    rows_with_errors integer NOT NULL,
    expected_clients integer NOT NULL,
    expected_cases integer NOT NULL,
    expected_transactions integer NOT NULL,
    expected_vendors integer NOT NULL,
    total_clients_in_csv integer NOT NULL,
    total_cases_in_csv integer NOT NULL,
    total_transactions_in_csv integer NOT NULL,
    total_vendors_in_csv integer NOT NULL,
    existing_clients integer NOT NULL,
    existing_cases integer NOT NULL,
    existing_vendors integer NOT NULL,
    preview_data text NOT NULL,
    preview_errors text NOT NULL,
    error_log text NOT NULL,
    imported_by character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone
);


ALTER TABLE public.import_audit OWNER TO iolta_user;

--
-- Name: import_audit_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.import_audit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_audit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_logs; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.import_logs (
    id bigint NOT NULL,
    import_type character varying(50) NOT NULL,
    filename character varying(255),
    status character varying(20) NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    total_rows integer,
    clients_created integer NOT NULL,
    clients_existing integer NOT NULL,
    cases_created integer NOT NULL,
    transactions_created integer NOT NULL,
    transactions_skipped integer NOT NULL,
    errors jsonb,
    summary jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer
);


ALTER TABLE public.import_logs OWNER TO iolta_user;

--
-- Name: import_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.import_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: law_firm; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.law_firm (
    id bigint NOT NULL,
    firm_name character varying(200) NOT NULL,
    doing_business_as character varying(200) NOT NULL,
    address_line1 character varying(100) NOT NULL,
    address_line2 character varying(100) NOT NULL,
    city character varying(50) NOT NULL,
    state character varying(2) NOT NULL,
    zip_code character varying(10) NOT NULL,
    phone character varying(20) NOT NULL,
    fax character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    website character varying(200) NOT NULL,
    principal_attorney character varying(100) NOT NULL,
    attorney_bar_number character varying(20) NOT NULL,
    attorney_state character varying(2) NOT NULL,
    trust_account_required boolean NOT NULL,
    iolta_compliant boolean NOT NULL,
    trust_account_certification_date date,
    tax_id character varying(20) NOT NULL,
    state_registration character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.law_firm OWNER TO iolta_user;

--
-- Name: law_firm_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.law_firm ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.law_firm_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.settings (
    id bigint NOT NULL,
    category character varying(50) NOT NULL,
    key character varying(100) NOT NULL,
    value character varying(255) NOT NULL,
    display_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.settings OWNER TO iolta_user;

--
-- Name: settings_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlement_distributions; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.settlement_distributions (
    id bigint NOT NULL,
    distribution_type character varying(20) NOT NULL,
    amount numeric(15,2) NOT NULL,
    description text,
    check_number character varying(50),
    is_paid boolean NOT NULL,
    paid_date date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint,
    settlement_id bigint NOT NULL,
    vendor_id bigint
);


ALTER TABLE public.settlement_distributions OWNER TO iolta_user;

--
-- Name: settlement_distributions_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.settlement_distributions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_distributions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlement_reconciliations; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.settlement_reconciliations (
    id bigint NOT NULL,
    bank_balance_before numeric(15,2) NOT NULL,
    bank_balance_after numeric(15,2) NOT NULL,
    client_balance_before numeric(15,2) NOT NULL,
    client_balance_after numeric(15,2) NOT NULL,
    total_distributions numeric(15,2) NOT NULL,
    reconciliation_status character varying(20) NOT NULL,
    reconciled_by character varying(100),
    reconciled_at timestamp with time zone,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    settlement_id bigint NOT NULL
);


ALTER TABLE public.settlement_reconciliations OWNER TO iolta_user;

--
-- Name: settlement_reconciliations_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.settlement_reconciliations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_reconciliations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlements; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.settlements (
    id bigint NOT NULL,
    settlement_number character varying(100),
    settlement_date date NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    status character varying(20) NOT NULL,
    notes text,
    created_by character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    bank_account_id bigint NOT NULL,
    case_id bigint,
    client_id bigint NOT NULL
);


ALTER TABLE public.settlements OWNER TO iolta_user;

--
-- Name: settlements_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_approvals; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.transaction_approvals (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    reviewed_at timestamp with time zone,
    status character varying(20) NOT NULL,
    request_notes text NOT NULL,
    review_notes text NOT NULL,
    ip_address inet,
    created_by_id integer NOT NULL,
    reviewed_by_id integer,
    transaction_id bigint NOT NULL,
    CONSTRAINT prevent_self_approval CHECK (((reviewed_by_id IS NULL) OR (NOT ((created_by_id = reviewed_by_id) AND (reviewed_by_id IS NOT NULL)))))
);


ALTER TABLE public.transaction_approvals OWNER TO iolta_user;

--
-- Name: transaction_approvals_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.transaction_approvals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_approvals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.user_profiles (
    id bigint NOT NULL,
    role character varying(30) NOT NULL,
    phone character varying(20) NOT NULL,
    employee_id character varying(50) NOT NULL,
    department character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    can_approve_transactions boolean NOT NULL,
    can_reconcile boolean NOT NULL,
    can_print_checks boolean NOT NULL,
    can_manage_users boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer,
    user_id integer NOT NULL
);


ALTER TABLE public.user_profiles OWNER TO iolta_user;

--
-- Name: user_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.user_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendor_types; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.vendor_types (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    is_active boolean NOT NULL,
    data_source character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.vendor_types OWNER TO iolta_user;

--
-- Name: vendor_types_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.vendor_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendors; Type: TABLE; Schema: public; Owner: iolta_user
--

CREATE TABLE public.vendors (
    id bigint NOT NULL,
    vendor_number character varying(50),
    vendor_name character varying(200) NOT NULL,
    contact_person character varying(200),
    email character varying(254),
    phone character varying(20),
    address text,
    city character varying(100),
    state character varying(2),
    zip_code character varying(20),
    tax_id character varying(50),
    is_active boolean NOT NULL,
    data_source character varying(20) NOT NULL,
    import_batch_id integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint,
    vendor_type_id bigint
);


ALTER TABLE public.vendors OWNER TO iolta_user;

--
-- Name: vendors_id_seq; Type: SEQUENCE; Schema: public; Owner: iolta_user
--

ALTER TABLE public.vendors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add case	7	add_case
26	Can change case	7	change_case
27	Can delete case	7	delete_case
28	Can view case	7	view_case
29	Can add client	8	add_client
30	Can change client	8	change_client
31	Can delete client	8	delete_client
32	Can view client	8	view_client
33	Can add vendor type	9	add_vendortype
34	Can change vendor type	9	change_vendortype
35	Can delete vendor type	9	delete_vendortype
36	Can view vendor type	9	view_vendortype
37	Can add vendor	10	add_vendor
38	Can change vendor	10	change_vendor
39	Can delete vendor	10	delete_vendor
40	Can view vendor	10	view_vendor
41	Can add bank account	11	add_bankaccount
42	Can change bank account	11	change_bankaccount
43	Can delete bank account	11	delete_bankaccount
44	Can view bank account	11	view_bankaccount
45	Can add bank transaction	12	add_banktransaction
46	Can change bank transaction	12	change_banktransaction
47	Can delete bank transaction	12	delete_banktransaction
48	Can view bank transaction	12	view_banktransaction
49	Can add bank reconciliation	13	add_bankreconciliation
50	Can change bank reconciliation	13	change_bankreconciliation
51	Can delete bank reconciliation	13	delete_bankreconciliation
52	Can view bank reconciliation	13	view_bankreconciliation
53	Can add Bank Transaction Audit Log	14	add_banktransactionaudit
54	Can change Bank Transaction Audit Log	14	change_banktransactionaudit
55	Can delete Bank Transaction Audit Log	14	delete_banktransactionaudit
56	Can view Bank Transaction Audit Log	14	view_banktransactionaudit
57	Can add settlement	15	add_settlement
58	Can change settlement	15	change_settlement
59	Can delete settlement	15	delete_settlement
60	Can view settlement	15	view_settlement
61	Can add settlement reconciliation	16	add_settlementreconciliation
62	Can change settlement reconciliation	16	change_settlementreconciliation
63	Can delete settlement reconciliation	16	delete_settlementreconciliation
64	Can view settlement reconciliation	16	view_settlementreconciliation
65	Can add settlement distribution	17	add_settlementdistribution
66	Can change settlement distribution	17	change_settlementdistribution
67	Can delete settlement distribution	17	delete_settlementdistribution
68	Can view settlement distribution	17	view_settlementdistribution
69	Can add Case Number Counter	18	add_casenumbercounter
70	Can change Case Number Counter	18	change_casenumbercounter
71	Can delete Case Number Counter	18	delete_casenumbercounter
72	Can view Case Number Counter	18	view_casenumbercounter
73	Can add Import Audit	19	add_importaudit
74	Can change Import Audit	19	change_importaudit
75	Can delete Import Audit	19	delete_importaudit
76	Can view Import Audit	19	view_importaudit
77	Can add Law Firm	20	add_lawfirm
78	Can change Law Firm	20	change_lawfirm
79	Can delete Law Firm	20	delete_lawfirm
80	Can view Law Firm	20	view_lawfirm
81	Can add User Profile	21	add_userprofile
82	Can change User Profile	21	change_userprofile
83	Can delete User Profile	21	delete_userprofile
84	Can view User Profile	21	view_userprofile
85	Can add setting	22	add_setting
86	Can change setting	22	change_setting
87	Can delete setting	22	delete_setting
88	Can view setting	22	view_setting
89	Can add Import Log	23	add_importlog
90	Can change Import Log	23	change_importlog
91	Can delete Import Log	23	delete_importlog
92	Can view Import Log	23	view_importlog
93	Can add Check Sequence	24	add_checksequence
94	Can change Check Sequence	24	change_checksequence
95	Can delete Check Sequence	24	delete_checksequence
96	Can view Check Sequence	24	view_checksequence
97	Can add staging client	25	add_stagingclient
98	Can change staging client	25	change_stagingclient
99	Can delete staging client	25	delete_stagingclient
100	Can view staging client	25	view_stagingclient
101	Can add staging case	26	add_stagingcase
102	Can change staging case	26	change_stagingcase
103	Can delete staging case	26	delete_stagingcase
104	Can view staging case	26	view_stagingcase
105	Can add staging bank transaction	27	add_stagingbanktransaction
106	Can change staging bank transaction	27	change_stagingbanktransaction
107	Can delete staging bank transaction	27	delete_stagingbanktransaction
108	Can view staging bank transaction	27	view_stagingbanktransaction
109	Can add import notification	28	add_importnotification
110	Can change import notification	28	change_importnotification
111	Can delete import notification	28	delete_importnotification
112	Can view import notification	28	view_importnotification
113	Can add Transaction Approval	29	add_transactionapproval
114	Can change Transaction Approval	29	change_transactionapproval
115	Can delete Transaction Approval	29	delete_transactionapproval
116	Can view Transaction Approval	29	view_transactionapproval
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$600000$4maxAgtLTtsNvVHI9iavr6$tlhcNa2fouu8HnGx/ytxPORm8pQ5YYCWcVdmwF5NoBM=	2025-11-27 11:55:12.123046+00	t	admin			admin@example.com	t	t	2025-11-27 06:42:27.43838+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: bank_accounts; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.bank_accounts (id, account_number, bank_name, bank_address, account_name, routing_number, account_type, opening_balance, next_check_number, is_active, created_at, updated_at) FROM stdin;
1	1234567890	Sample Bank	\N	IOLTA Trust Account	021000021	checking	0.00	1001	t	2025-11-27 12:02:50.960464+00	2025-11-27 12:02:50.960464+00
\.


--
-- Data for Name: bank_reconciliations; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.bank_reconciliations (id, reconciliation_date, statement_balance, book_balance, is_reconciled, reconciled_by, reconciled_at, notes, created_at, updated_at, bank_account_id) FROM stdin;
\.


--
-- Data for Name: bank_transaction_audit; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.bank_transaction_audit (id, action, action_date, action_by, old_values, new_values, old_amount, new_amount, old_status, new_status, change_reason, ip_address, transaction_id) FROM stdin;
\.


--
-- Data for Name: bank_transactions; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.bank_transactions (id, transaction_number, transaction_date, transaction_type, amount, description, check_memo, reference_number, payee, item_type, cleared_date, check_is_printed, voided_date, voided_by, void_reason, post_date, bank_reference, bank_category, status, reconciliation_notes, rec_id, data_source, import_batch_id, created_at, updated_at, created_by, original_transaction_id, original_item_id, bank_account_id, case_id, client_id, vendor_id, check_number) FROM stdin;
\.


--
-- Data for Name: case_number_counter; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.case_number_counter (id, last_number) FROM stdin;
\.


--
-- Data for Name: cases; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.cases (id, case_number, case_title, case_description, case_amount, case_status, opened_date, closed_date, is_active, data_source, import_batch_id, created_at, updated_at, client_id) FROM stdin;
\.


--
-- Data for Name: check_sequences; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.check_sequences (id, next_check_number, last_assigned_number, last_assigned_date, bank_account_id) FROM stdin;
\.


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.clients (id, client_number, client_name, email, phone, address, city, state, zip_code, trust_account_status, is_active, data_source, import_batch_id, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: clients_assigned_users; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.clients_assigned_users (id, client_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	clients	case
8	clients	client
9	vendors	vendortype
10	vendors	vendor
11	bank_accounts	bankaccount
12	bank_accounts	banktransaction
13	bank_accounts	bankreconciliation
14	bank_accounts	banktransactionaudit
15	settlements	settlement
16	settlements	settlementreconciliation
17	settlements	settlementdistribution
18	settings	casenumbercounter
19	settings	importaudit
20	settings	lawfirm
21	settings	userprofile
22	settings	setting
23	settings	importlog
24	settings	checksequence
25	imports	stagingclient
26	imports	stagingcase
27	imports	stagingbanktransaction
28	imports	importnotification
29	bank_accounts	transactionapproval
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-11-26 08:02:12.73618+00
2	auth	0001_initial	2025-11-26 08:02:12.756167+00
3	admin	0001_initial	2025-11-26 08:02:12.762214+00
4	admin	0002_logentry_remove_auto_add	2025-11-26 08:02:12.764371+00
5	admin	0003_logentry_add_action_flag_choices	2025-11-26 08:02:12.766341+00
6	contenttypes	0002_remove_content_type_name	2025-11-26 08:02:12.770191+00
7	auth	0002_alter_permission_name_max_length	2025-11-26 08:02:12.772259+00
8	auth	0003_alter_user_email_max_length	2025-11-26 08:02:12.774297+00
9	auth	0004_alter_user_username_opts	2025-11-26 08:02:12.776838+00
10	auth	0005_alter_user_last_login_null	2025-11-26 08:02:12.778739+00
11	auth	0006_require_contenttypes_0002	2025-11-26 08:02:12.779283+00
12	auth	0007_alter_validators_add_error_messages	2025-11-26 08:02:12.781456+00
13	auth	0008_alter_user_username_max_length	2025-11-26 08:02:12.784657+00
14	auth	0009_alter_user_last_name_max_length	2025-11-26 08:02:12.786801+00
15	auth	0010_alter_group_name_max_length	2025-11-26 08:02:12.789218+00
16	auth	0011_update_proxy_permissions	2025-11-26 08:02:12.791144+00
17	auth	0012_alter_user_first_name_max_length	2025-11-26 08:02:12.793105+00
18	clients	0001_initial	2025-11-26 08:02:12.802326+00
19	vendors	0001_initial	2025-11-26 08:02:12.811777+00
20	bank_accounts	0001_initial	2025-11-26 08:02:12.864721+00
21	sessions	0001_initial	2025-11-26 08:02:12.868384+00
22	settings	0001_initial	2025-11-26 08:02:12.889793+00
23	settlements	0001_initial	2025-11-26 08:02:12.910994+00
24	bank_accounts	0002_remove_check_number	2025-11-26 08:53:39.821379+00
25	bank_accounts	0003_remove_banktransaction_bank_transa_check_n_eca858_idx	2025-11-27 07:31:44.842982+00
26	bank_accounts	0003_banktransaction_check_number_transactionapproval_and_more	2025-11-27 07:48:52.920227+00
27	clients	0002_add_assigned_users_idor_protection	2025-11-27 08:52:51.587251+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
yzio3vyrds85co7kmmx4kbv8gqc96kg2	.eJxtj01qAzEMhe_idTCWHP9l11yhBzCuojBOYSbY8qKE3L0e6KKBLCSE9N4n6aFyGbLk0bnlelEnBerwv_dV6JvXfSBtdMmFaBur5HvbbkyiO9NoVX70517wxzTyKpWK1G09_5lfiEvpy8SlGInIG5g5GlOch2SNs8gO_dUQgQvgA0MAa6y3ySNMWcSYjlcm3qGyNC6SLyzzlLkv1_v-gQMNZgZGjWjfCruUJuoEwR_RWuejDikhhvD8BWUqWFw:1vOXx2:LB7nWex_o2h6iHFJNlstOTqU8htpu0IU_ITYaNcJsAg	2025-11-27 17:06:08.250989+00
joaszsts9xcr10qwc5modjn3212qj5x3	.eJxVjEsOAiEQRO_C2kxokJ87vYIHINj2ZNCEMdAsjPHuMokL3VQqVfXqJWLqvMTeqMZ8FQcBYvebXRLeqWwF1944JsS1F46Put4IeWqEvWZ-TufN0HGAVDhj4ryW0xf-e1xSW8Zd8B4RrYShXspkLAQtjVZklJ0lIhgH1hE40FJbHayCMfPKh_1MSOL9AdgEPlo:1vOX7k:_T3smi5lyA1JfG3CtIEUS3OTYwzBVuUvTib7lJwPyq8	2025-11-27 16:13:08.000653+00
ikeoe4yr0p4g8cbecx5972in2xsqrval	.eJxtjktqBDEMRO_idTCW_55d5go5gHE0GtoJdA-2vAghd48askggGyFUVa_0qWpbvNU1adR-UxcF6un37bXhO-2nwGNNrg3xWDvXxzjeCFlPwjU6f-iXc6FnCdLOHRv3Y7_-hP8QtzY3wZWcETEakJmNaSFCcSY4S8HGu0GEkCAmggTOuOhKtCC2bHPxd0I6obwNalxvxPKK9NX-ELIP2nqvwSadwr-2yW2wukCKXpw-ScDkIh1f38LaWAM:1vOadS:84uuCDh8Kut8B8xVAxJjfGFUSleAanDuE9LDUKVKtHE	2025-11-27 19:58:06.570284+00
7ae2fmvfyoasvfcpbyhucc5sm25w3ya4	.eJxtjk1qAzEMRu_idTGWf2RPds0VcgDjKgrjFmaCLS9C6d3rgS4ayEYI6X1P-la5DFnz6NxyvaqTAvX2f_ZR6Iu3YyFtdMmFaB-b5HvbP5lEd6bRqjz05Wj4fQZ5k0pF6r6d_8JPxrX0deqWlIgIDcyajCkBYXEmOMvB4s0QQYiAkSGCMw7dghYmlmxa_I2JD6msjYvkK8t8Zd7L9T7NPmjrvQYbdQwvsS6liTpBRD_JAFaHiGhi_PkFwqRX_A:1vOay0:Zr9yidjiZqQpnSTMdgc756xVHdKkl8GT0kWT5VpBlF0	2025-11-27 20:19:20.291493+00
pdwkg18s7bouhrfynzdacxqsltrd0zkf	.eJxtj81KRDEMhd-laylNf9J2ds4r-AClZjLcKtw7tOlCxHe3F1wouAkhOec7yacqdcpW5uBe2k1dFKin37PXSu-8nwvpc0ipRMfcpTz68cYkejDN3uRDv5wNPy8j79KoSjv264_5D3GrY1u4nBIRoYFVkzE1IGRngrMcLN4NEYQIGBkiOOPQZbSwZMmm7O9MfEJl61yl3FjWKSuvtMf5QUYNNmkLTqP5VzekdlEXiOit9y6AdhGsz_HrGxTSWCY:1vOcwB:pt-Vb48KuhVBkuu35Y3JTXN4rTYsXXjCbzcuaqYCqks	2025-11-27 22:25:35.844089+00
ia79bjzylhculocegowonaho7rah4p7q	.eJxtjkFqAzEMRe_idTGWPdbY2SVX6AGMq1EYNzATbHlRQu5eD2SRQjdCfP3_vh4q5S5r6o1rKos6KVAf79pXphtvx0Fqb5Iy0d43Sfe6fzOJbky9FvnRn8fC5xHkTQplKft2eYX_ENfc1oGLIRARGhgzGJM9QnTGO8ve4tUQgZ8BZ4YZnHHoIloYtmBDnK5MfEBlrZwlLSzjldGXyn2QJ9DWWR2DBhf-tTXJVdQJZpzsZBBR--AG3j5_AcKGV_E:1vOe19:RAaRb47TSVLvEOP0HXY6L_Ml3sF8vG9tZq7u0kG04X4	2025-11-27 23:34:47.045567+00
\.


--
-- Data for Name: import_audit; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.import_audit (id, import_date, import_type, file_name, status, total_records, successful_records, failed_records, clients_created, cases_created, transactions_created, vendors_created, clients_skipped, cases_skipped, vendors_skipped, rows_with_errors, expected_clients, expected_cases, expected_transactions, expected_vendors, total_clients_in_csv, total_cases_in_csv, total_transactions_in_csv, total_vendors_in_csv, existing_clients, existing_cases, existing_vendors, preview_data, preview_errors, error_log, imported_by, created_at, completed_at) FROM stdin;
\.


--
-- Data for Name: import_logs; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.import_logs (id, import_type, filename, status, started_at, completed_at, total_rows, clients_created, clients_existing, cases_created, transactions_created, transactions_skipped, errors, summary, created_at, updated_at, created_by_id) FROM stdin;
\.


--
-- Data for Name: law_firm; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.law_firm (id, firm_name, doing_business_as, address_line1, address_line2, city, state, zip_code, phone, fax, email, website, principal_attorney, attorney_bar_number, attorney_state, trust_account_required, iolta_compliant, trust_account_certification_date, tax_id, state_registration, is_active, created_at, updated_at) FROM stdin;
1	Sample Law Firm	Sample Law Firm	123 Main Street		New York	NY	10001	(555) 123-4567		info@samplelawfirm.com		John Doe			f	f	\N			t	2025-11-27 12:03:31.298305+00	2025-11-27 12:03:31.298305+00
\.


--
-- Data for Name: settings; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.settings (id, category, key, value, display_order, is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: settlement_distributions; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.settlement_distributions (id, distribution_type, amount, description, check_number, is_paid, paid_date, created_at, updated_at, client_id, settlement_id, vendor_id) FROM stdin;
\.


--
-- Data for Name: settlement_reconciliations; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.settlement_reconciliations (id, bank_balance_before, bank_balance_after, client_balance_before, client_balance_after, total_distributions, reconciliation_status, reconciled_by, reconciled_at, notes, created_at, updated_at, settlement_id) FROM stdin;
\.


--
-- Data for Name: settlements; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.settlements (id, settlement_number, settlement_date, total_amount, status, notes, created_by, created_at, updated_at, bank_account_id, case_id, client_id) FROM stdin;
\.


--
-- Data for Name: transaction_approvals; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.transaction_approvals (id, created_at, reviewed_at, status, request_notes, review_notes, ip_address, created_by_id, reviewed_by_id, transaction_id) FROM stdin;
\.


--
-- Data for Name: user_profiles; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.user_profiles (id, role, phone, employee_id, department, is_active, can_approve_transactions, can_reconcile, can_print_checks, can_manage_users, created_at, updated_at, created_by_id, user_id) FROM stdin;
1	paralegal				t	f	f	f	f	2025-11-27 06:42:27.497111+00	2025-11-27 06:42:27.497115+00	\N	1
\.


--
-- Data for Name: vendor_types; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.vendor_types (id, name, description, is_active, data_source, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: vendors; Type: TABLE DATA; Schema: public; Owner: iolta_user
--

COPY public.vendors (id, vendor_number, vendor_name, contact_person, email, phone, address, city, state, zip_code, tax_id, is_active, data_source, import_batch_id, created_at, updated_at, client_id, vendor_type_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 116, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: bank_accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.bank_accounts_id_seq', 2, true);


--
-- Name: bank_reconciliations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.bank_reconciliations_id_seq', 1, false);


--
-- Name: bank_transaction_audit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.bank_transaction_audit_id_seq', 1, true);


--
-- Name: bank_transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.bank_transactions_id_seq', 2, true);


--
-- Name: case_number_counter_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.case_number_counter_id_seq', 1, false);


--
-- Name: cases_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.cases_id_seq', 1, false);


--
-- Name: check_sequences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.check_sequences_id_seq', 1, false);


--
-- Name: clients_assigned_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.clients_assigned_users_id_seq', 1, false);


--
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.clients_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 29, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- Name: import_audit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.import_audit_id_seq', 1, false);


--
-- Name: import_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.import_logs_id_seq', 1, true);


--
-- Name: law_firm_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.law_firm_id_seq', 1, false);


--
-- Name: settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.settings_id_seq', 1, false);


--
-- Name: settlement_distributions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.settlement_distributions_id_seq', 1, false);


--
-- Name: settlement_reconciliations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.settlement_reconciliations_id_seq', 1, false);


--
-- Name: settlements_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.settlements_id_seq', 1, false);


--
-- Name: transaction_approvals_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.transaction_approvals_id_seq', 1, false);


--
-- Name: user_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.user_profiles_id_seq', 1, true);


--
-- Name: vendor_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.vendor_types_id_seq', 1, false);


--
-- Name: vendors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iolta_user
--

SELECT pg_catalog.setval('public.vendors_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: bank_accounts bank_accounts_account_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_accounts
    ADD CONSTRAINT bank_accounts_account_number_key UNIQUE (account_number);


--
-- Name: bank_accounts bank_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_accounts
    ADD CONSTRAINT bank_accounts_pkey PRIMARY KEY (id);


--
-- Name: bank_reconciliations bank_reconciliations_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_reconciliations
    ADD CONSTRAINT bank_reconciliations_pkey PRIMARY KEY (id);


--
-- Name: bank_transaction_audit bank_transaction_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transaction_audit
    ADD CONSTRAINT bank_transaction_audit_pkey PRIMARY KEY (id);


--
-- Name: bank_transactions bank_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_pkey PRIMARY KEY (id);


--
-- Name: bank_transactions bank_transactions_transaction_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_transaction_number_key UNIQUE (transaction_number);


--
-- Name: case_number_counter case_number_counter_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.case_number_counter
    ADD CONSTRAINT case_number_counter_pkey PRIMARY KEY (id);


--
-- Name: cases cases_case_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.cases
    ADD CONSTRAINT cases_case_number_key UNIQUE (case_number);


--
-- Name: cases cases_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.cases
    ADD CONSTRAINT cases_pkey PRIMARY KEY (id);


--
-- Name: check_sequences check_sequences_bank_account_id_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.check_sequences
    ADD CONSTRAINT check_sequences_bank_account_id_key UNIQUE (bank_account_id);


--
-- Name: check_sequences check_sequences_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.check_sequences
    ADD CONSTRAINT check_sequences_pkey PRIMARY KEY (id);


--
-- Name: clients_assigned_users clients_assigned_users_client_id_user_id_0302cd69_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.clients_assigned_users
    ADD CONSTRAINT clients_assigned_users_client_id_user_id_0302cd69_uniq UNIQUE (client_id, user_id);


--
-- Name: clients_assigned_users clients_assigned_users_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.clients_assigned_users
    ADD CONSTRAINT clients_assigned_users_pkey PRIMARY KEY (id);


--
-- Name: clients clients_client_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_client_number_key UNIQUE (client_number);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: import_audit import_audit_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.import_audit
    ADD CONSTRAINT import_audit_pkey PRIMARY KEY (id);


--
-- Name: import_logs import_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.import_logs
    ADD CONSTRAINT import_logs_pkey PRIMARY KEY (id);


--
-- Name: law_firm law_firm_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.law_firm
    ADD CONSTRAINT law_firm_pkey PRIMARY KEY (id);


--
-- Name: settings settings_category_key_db3f85ba_uniq; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_category_key_db3f85ba_uniq UNIQUE (category, key);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (id);


--
-- Name: settlement_distributions settlement_distributions_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_distributions
    ADD CONSTRAINT settlement_distributions_pkey PRIMARY KEY (id);


--
-- Name: settlement_reconciliations settlement_reconciliations_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_reconciliations
    ADD CONSTRAINT settlement_reconciliations_pkey PRIMARY KEY (id);


--
-- Name: settlement_reconciliations settlement_reconciliations_settlement_id_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_reconciliations
    ADD CONSTRAINT settlement_reconciliations_settlement_id_key UNIQUE (settlement_id);


--
-- Name: settlements settlements_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_pkey PRIMARY KEY (id);


--
-- Name: settlements settlements_settlement_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_settlement_number_key UNIQUE (settlement_number);


--
-- Name: transaction_approvals transaction_approvals_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.transaction_approvals
    ADD CONSTRAINT transaction_approvals_pkey PRIMARY KEY (id);


--
-- Name: transaction_approvals transaction_approvals_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.transaction_approvals
    ADD CONSTRAINT transaction_approvals_transaction_id_key UNIQUE (transaction_id);


--
-- Name: clients unique_client_name; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT unique_client_name UNIQUE (client_name);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);


--
-- Name: user_profiles user_profiles_user_id_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_key UNIQUE (user_id);


--
-- Name: vendor_types vendor_types_name_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendor_types
    ADD CONSTRAINT vendor_types_name_key UNIQUE (name);


--
-- Name: vendor_types vendor_types_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendor_types
    ADD CONSTRAINT vendor_types_pkey PRIMARY KEY (id);


--
-- Name: vendors vendors_pkey; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_pkey PRIMARY KEY (id);


--
-- Name: vendors vendors_vendor_number_key; Type: CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_vendor_number_key UNIQUE (vendor_number);


--
-- Name: audit_action_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX audit_action_idx ON public.bank_transaction_audit USING btree (action);


--
-- Name: audit_date_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX audit_date_idx ON public.bank_transaction_audit USING btree (action_date);


--
-- Name: audit_trans_date_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX audit_trans_date_idx ON public.bank_transaction_audit USING btree (transaction_id, action_date DESC);


--
-- Name: audit_user_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX audit_user_idx ON public.bank_transaction_audit USING btree (action_by);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: bank_accounts_account_number_c5d2f925_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_accounts_account_number_c5d2f925_like ON public.bank_accounts USING btree (account_number varchar_pattern_ops);


--
-- Name: bank_reconciliations_bank_account_id_c56ef498; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_reconciliations_bank_account_id_c56ef498 ON public.bank_reconciliations USING btree (bank_account_id);


--
-- Name: bank_transa_bank_ac_89ae9f_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_bank_ac_89ae9f_idx ON public.bank_transactions USING btree (bank_account_id, transaction_date);


--
-- Name: bank_transa_case_id_7c7fc6_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_case_id_7c7fc6_idx ON public.bank_transactions USING btree (case_id);


--
-- Name: bank_transa_client__d9d9d7_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_client__d9d9d7_idx ON public.bank_transactions USING btree (client_id);


--
-- Name: bank_transa_referen_cb533e_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_referen_cb533e_idx ON public.bank_transactions USING btree (reference_number);


--
-- Name: bank_transa_status_a92de8_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_status_a92de8_idx ON public.bank_transactions USING btree (status, transaction_date);


--
-- Name: bank_transa_status_b8b399_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_status_b8b399_idx ON public.bank_transactions USING btree (status);


--
-- Name: bank_transa_transac_a4828a_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_transac_a4828a_idx ON public.bank_transactions USING btree (transaction_number);


--
-- Name: bank_transa_transac_a87669_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_transac_a87669_idx ON public.bank_transactions USING btree (transaction_date, transaction_type);


--
-- Name: bank_transa_vendor__92455e_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transa_vendor__92455e_idx ON public.bank_transactions USING btree (vendor_id);


--
-- Name: bank_transaction_audit_transaction_id_8fd3002a; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transaction_audit_transaction_id_8fd3002a ON public.bank_transaction_audit USING btree (transaction_id);


--
-- Name: bank_transactions_bank_account_id_66f7cc01; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transactions_bank_account_id_66f7cc01 ON public.bank_transactions USING btree (bank_account_id);


--
-- Name: bank_transactions_case_id_6affebb3; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transactions_case_id_6affebb3 ON public.bank_transactions USING btree (case_id);


--
-- Name: bank_transactions_client_id_405c5e3b; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transactions_client_id_405c5e3b ON public.bank_transactions USING btree (client_id);


--
-- Name: bank_transactions_transaction_number_b51b6526_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transactions_transaction_number_b51b6526_like ON public.bank_transactions USING btree (transaction_number varchar_pattern_ops);


--
-- Name: bank_transactions_vendor_id_da6a5c0d; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX bank_transactions_vendor_id_da6a5c0d ON public.bank_transactions USING btree (vendor_id);


--
-- Name: cases_case_number_a80b753e_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX cases_case_number_a80b753e_like ON public.cases USING btree (case_number varchar_pattern_ops);


--
-- Name: cases_client_id_fcf3eac3; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX cases_client_id_fcf3eac3 ON public.cases USING btree (client_id);


--
-- Name: clients_assigned_users_client_id_9836875a; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX clients_assigned_users_client_id_9836875a ON public.clients_assigned_users USING btree (client_id);


--
-- Name: clients_assigned_users_user_id_d757dfdd; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX clients_assigned_users_user_id_d757dfdd ON public.clients_assigned_users USING btree (user_id);


--
-- Name: clients_client_number_0055cce2_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX clients_client_number_0055cce2_like ON public.clients USING btree (client_number varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: import_logs_created_by_id_5a65dd9a; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX import_logs_created_by_id_5a65dd9a ON public.import_logs USING btree (created_by_id);


--
-- Name: settlement_distributions_client_id_23cf5585; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlement_distributions_client_id_23cf5585 ON public.settlement_distributions USING btree (client_id);


--
-- Name: settlement_distributions_settlement_id_204f0ace; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlement_distributions_settlement_id_204f0ace ON public.settlement_distributions USING btree (settlement_id);


--
-- Name: settlement_distributions_vendor_id_dbb05069; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlement_distributions_vendor_id_dbb05069 ON public.settlement_distributions USING btree (vendor_id);


--
-- Name: settlements_bank_account_id_10bf7939; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlements_bank_account_id_10bf7939 ON public.settlements USING btree (bank_account_id);


--
-- Name: settlements_case_id_5616be20; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlements_case_id_5616be20 ON public.settlements USING btree (case_id);


--
-- Name: settlements_client_id_58af542e; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlements_client_id_58af542e ON public.settlements USING btree (client_id);


--
-- Name: settlements_settlement_number_2b9b9f04_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX settlements_settlement_number_2b9b9f04_like ON public.settlements USING btree (settlement_number varchar_pattern_ops);


--
-- Name: transaction_approvals_created_by_id_64b6d531; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_approvals_created_by_id_64b6d531 ON public.transaction_approvals USING btree (created_by_id);


--
-- Name: transaction_approvals_reviewed_by_id_e9cd8251; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_approvals_reviewed_by_id_e9cd8251 ON public.transaction_approvals USING btree (reviewed_by_id);


--
-- Name: transaction_approvals_status_7cf81d68; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_approvals_status_7cf81d68 ON public.transaction_approvals USING btree (status);


--
-- Name: transaction_approvals_status_7cf81d68_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_approvals_status_7cf81d68_like ON public.transaction_approvals USING btree (status varchar_pattern_ops);


--
-- Name: transaction_created_08a22b_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_created_08a22b_idx ON public.transaction_approvals USING btree (created_by_id, status);


--
-- Name: transaction_reviewe_12700f_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_reviewe_12700f_idx ON public.transaction_approvals USING btree (reviewed_by_id, status);


--
-- Name: transaction_status_d64ec1_idx; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX transaction_status_d64ec1_idx ON public.transaction_approvals USING btree (status, created_at DESC);


--
-- Name: user_profiles_created_by_id_e23d6f71; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX user_profiles_created_by_id_e23d6f71 ON public.user_profiles USING btree (created_by_id);


--
-- Name: vendor_types_name_a158871a_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX vendor_types_name_a158871a_like ON public.vendor_types USING btree (name varchar_pattern_ops);


--
-- Name: vendors_client_id_9964fb3b; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX vendors_client_id_9964fb3b ON public.vendors USING btree (client_id);


--
-- Name: vendors_vendor_number_f40f56ef_like; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX vendors_vendor_number_f40f56ef_like ON public.vendors USING btree (vendor_number varchar_pattern_ops);


--
-- Name: vendors_vendor_type_id_aa46b9df; Type: INDEX; Schema: public; Owner: iolta_user
--

CREATE INDEX vendors_vendor_type_id_aa46b9df ON public.vendors USING btree (vendor_type_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_reconciliations bank_reconciliations_bank_account_id_c56ef498_fk_bank_acco; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_reconciliations
    ADD CONSTRAINT bank_reconciliations_bank_account_id_c56ef498_fk_bank_acco FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_transaction_audit bank_transaction_aud_transaction_id_8fd3002a_fk_bank_tran; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transaction_audit
    ADD CONSTRAINT bank_transaction_aud_transaction_id_8fd3002a_fk_bank_tran FOREIGN KEY (transaction_id) REFERENCES public.bank_transactions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_transactions bank_transactions_bank_account_id_66f7cc01_fk_bank_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_bank_account_id_66f7cc01_fk_bank_accounts_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_transactions bank_transactions_case_id_6affebb3_fk_cases_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_case_id_6affebb3_fk_cases_id FOREIGN KEY (case_id) REFERENCES public.cases(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_transactions bank_transactions_client_id_405c5e3b_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_client_id_405c5e3b_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bank_transactions bank_transactions_vendor_id_da6a5c0d_fk_vendors_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.bank_transactions
    ADD CONSTRAINT bank_transactions_vendor_id_da6a5c0d_fk_vendors_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cases cases_client_id_fcf3eac3_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.cases
    ADD CONSTRAINT cases_client_id_fcf3eac3_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: check_sequences check_sequences_bank_account_id_7ade4d4f_fk_bank_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.check_sequences
    ADD CONSTRAINT check_sequences_bank_account_id_7ade4d4f_fk_bank_accounts_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clients_assigned_users clients_assigned_users_client_id_9836875a_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.clients_assigned_users
    ADD CONSTRAINT clients_assigned_users_client_id_9836875a_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clients_assigned_users clients_assigned_users_user_id_d757dfdd_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.clients_assigned_users
    ADD CONSTRAINT clients_assigned_users_user_id_d757dfdd_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: import_logs import_logs_created_by_id_5a65dd9a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.import_logs
    ADD CONSTRAINT import_logs_created_by_id_5a65dd9a_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlement_distributions settlement_distribut_settlement_id_204f0ace_fk_settlemen; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_distributions
    ADD CONSTRAINT settlement_distribut_settlement_id_204f0ace_fk_settlemen FOREIGN KEY (settlement_id) REFERENCES public.settlements(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlement_distributions settlement_distributions_client_id_23cf5585_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_distributions
    ADD CONSTRAINT settlement_distributions_client_id_23cf5585_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlement_distributions settlement_distributions_vendor_id_dbb05069_fk_vendors_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_distributions
    ADD CONSTRAINT settlement_distributions_vendor_id_dbb05069_fk_vendors_id FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlement_reconciliations settlement_reconcili_settlement_id_072637c7_fk_settlemen; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlement_reconciliations
    ADD CONSTRAINT settlement_reconcili_settlement_id_072637c7_fk_settlemen FOREIGN KEY (settlement_id) REFERENCES public.settlements(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlements settlements_bank_account_id_10bf7939_fk_bank_accounts_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_bank_account_id_10bf7939_fk_bank_accounts_id FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlements settlements_case_id_5616be20_fk_cases_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_case_id_5616be20_fk_cases_id FOREIGN KEY (case_id) REFERENCES public.cases(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: settlements settlements_client_id_58af542e_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_client_id_58af542e_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaction_approvals transaction_approval_transaction_id_091f992e_fk_bank_tran; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.transaction_approvals
    ADD CONSTRAINT transaction_approval_transaction_id_091f992e_fk_bank_tran FOREIGN KEY (transaction_id) REFERENCES public.bank_transactions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaction_approvals transaction_approvals_created_by_id_64b6d531_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.transaction_approvals
    ADD CONSTRAINT transaction_approvals_created_by_id_64b6d531_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transaction_approvals transaction_approvals_reviewed_by_id_e9cd8251_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.transaction_approvals
    ADD CONSTRAINT transaction_approvals_reviewed_by_id_e9cd8251_fk_auth_user_id FOREIGN KEY (reviewed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_profiles user_profiles_created_by_id_e23d6f71_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_created_by_id_e23d6f71_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_profiles user_profiles_user_id_8c5ab5fe_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_8c5ab5fe_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vendors vendors_client_id_9964fb3b_fk_clients_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_client_id_9964fb3b_fk_clients_id FOREIGN KEY (client_id) REFERENCES public.clients(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vendors vendors_vendor_type_id_aa46b9df_fk_vendor_types_id; Type: FK CONSTRAINT; Schema: public; Owner: iolta_user
--

ALTER TABLE ONLY public.vendors
    ADD CONSTRAINT vendors_vendor_type_id_aa46b9df_fk_vendor_types_id FOREIGN KEY (vendor_type_id) REFERENCES public.vendor_types(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: iolta_user
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict MFn0vEyxGEB8peGuKhFi4fDzrgNx0ZAW3VMQpOd4eACXiFWXwV8ppnwmvl6eMWx

