# Generated by Django 4.2.7 on 2025-11-26 08:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=100, unique=True)),
                ('case_title', models.CharField(max_length=255, verbose_name='Case Title')),
                ('case_description', models.TextField(blank=True, null=True)),
                ('case_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('case_status', models.CharField(choices=[('Open', 'Open'), ('Pending Settlement', 'Pending Settlement'), ('Settled', 'Settled'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_source', models.CharField(choices=[('webapp', 'Web Application'), ('csv_import', 'CSV Import'), ('api_import', 'API Import')], default='webapp', help_text='Source of data entry', max_length=20)),
                ('import_batch_id', models.IntegerField(blank=True, help_text='Links to ImportAudit record', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-opened_date', 'case_number'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in US format: (123) 456-7890, 123-456-7890, or +1234567890', regex='^(\\+?1[-.\\s]?)?\\(?[0-9]{3}\\)?[-.\\s]?[0-9]{3}[-.\\s]?[0-9]{4}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, choices=[('', 'Select State'), ('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY'), ('DC', 'DC')], max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('trust_account_status', models.CharField(choices=[('ACTIVE_WITH_FUNDS', 'Active with Funds'), ('ACTIVE_ZERO_BALANCE', 'Active - Zero Balance'), ('DORMANT', 'Dormant (No Activity 2+ Years)'), ('NEGATIVE_BALANCE', 'Negative Balance'), ('CLOSED', 'Closed/Inactive')], default='ACTIVE_ZERO_BALANCE', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('data_source', models.CharField(choices=[('webapp', 'Web Application'), ('csv_import', 'CSV Import'), ('api_import', 'API Import')], default='webapp', help_text='Source of data entry', max_length=20)),
                ('import_batch_id', models.IntegerField(blank=True, help_text='Links to ImportAudit record', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['client_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('client_name',), name='unique_client_name'),
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client'),
        ),
    ]
