# Generated by Django 4.2.7 on 2025-11-26 08:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vendors', '0001_initial'),
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('settlement_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_accounts.bankaccount')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
            options={
                'db_table': 'settlements',
                'ordering': ['-settlement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bank_balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client_balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client_balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_distributions', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reconciliation_status', models.CharField(choices=[('PENDING', 'Pending'), ('BALANCED', 'Balanced'), ('UNBALANCED', 'Unbalanced'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('reconciled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='settlements.settlement')),
            ],
            options={
                'db_table': 'settlement_reconciliations',
                'ordering': ['-reconciled_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_type', models.CharField(choices=[('VENDOR_PAYMENT', 'Vendor Payment'), ('CLIENT_REFUND', 'Client Refund'), ('ATTORNEY_FEES', 'Attorney Fees'), ('COURT_COSTS', 'Court Costs'), ('MEDICAL_EXPENSES', 'Medical Expenses'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='settlements.settlement')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendors.vendor')),
            ],
            options={
                'db_table': 'settlement_distributions',
                'ordering': ['settlement', 'distribution_type'],
            },
        ),
    ]
