# Generated by Django 4.2.7 on 2025-11-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_address', models.TextField(blank=True, null=True)),
                ('account_name', models.CharField(max_length=200)),
                ('routing_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(choices=[('Trust Account', 'Trust Account'), ('Operating Account', 'Operating Account'), ('Escrow Account', 'Escrow Account')], default='Trust Account', max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('next_check_number', models.IntegerField(default=1001, help_text='Next sequential check number for IOLTA compliance')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank_accounts',
                'ordering': ['bank_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('check_memo', models.CharField(blank=True, max_length=500)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference (check number for withdrawals, receipt for deposits)', max_length=100)),
                ('check_number', models.CharField(blank=True, help_text='DEPRECATED: Use reference_number instead', max_length=50)),
                ('payee', models.CharField(blank=True, max_length=255)),
                ('item_type', models.CharField(blank=True, choices=[('CLIENT_DEPOSIT', 'Client Deposit'), ('VENDOR_PAYMENT', 'Vendor Payment'), ('CASE_SETTLEMENT', 'Case Settlement'), ('BANK_FEE', 'Bank Fee'), ('INTEREST', 'Interest'), ('OTHER', 'Other')], max_length=20)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('check_is_printed', models.BooleanField(default=False)),
                ('voided_date', models.DateTimeField(blank=True, null=True)),
                ('voided_by', models.CharField(blank=True, max_length=100)),
                ('void_reason', models.TextField(blank=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('bank_category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('voided', 'Voided'), ('reconciled', 'Reconciled')], default='pending', max_length=20)),
                ('reconciliation_notes', models.TextField(blank=True)),
                ('rec_id', models.IntegerField(blank=True, null=True)),
                ('data_source', models.CharField(choices=[('webapp', 'Web Application'), ('csv_import', 'CSV Import'), ('api_import', 'API Import')], default='webapp', help_text='Source of data entry', max_length=20)),
                ('import_batch_id', models.IntegerField(blank=True, help_text='Links to ImportAudit record', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('original_transaction_id', models.IntegerField(blank=True, null=True)),
                ('original_item_id', models.IntegerField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='bank_accounts.bankaccount')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='clients.case')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='clients.client')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='vendors.vendor')),
            ],
            options={
                'db_table': 'bank_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.bankaccount')),
            ],
            options={
                'db_table': 'bank_reconciliations',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='BankTransactionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('CLEARED', 'Cleared'), ('VOIDED', 'Voided'), ('UNVOIDED', 'Unvoided'), ('DELETED', 'Deleted')], help_text='Type of action performed', max_length=20)),
                ('action_date', models.DateTimeField(auto_now_add=True, help_text='When this action occurred')),
                ('action_by', models.CharField(help_text='Username of person who made the change', max_length=100)),
                ('old_values', models.JSONField(blank=True, help_text='Complete snapshot of values BEFORE change', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Complete snapshot of values AFTER change', null=True)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount before change', max_digits=15, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount after change', max_digits=15, null=True)),
                ('old_status', models.CharField(blank=True, help_text='Status before change (pending/cleared/voided)', max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, help_text='Status after change (pending/cleared/voided)', max_length=20, null=True)),
                ('change_reason', models.TextField(blank=True, help_text='Reason for the change (required for voids)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of user who made the change', null=True)),
                ('transaction', models.ForeignKey(help_text='Transaction this audit log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bank_accounts.banktransaction')),
            ],
            options={
                'verbose_name': 'Bank Transaction Audit Log',
                'verbose_name_plural': 'Bank Transaction Audit Logs',
                'db_table': 'bank_transaction_audit',
                'ordering': ['-action_date'],
                'indexes': [models.Index(fields=['transaction', '-action_date'], name='audit_trans_date_idx'), models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['action_by'], name='audit_user_idx'), models.Index(fields=['action_date'], name='audit_date_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', 'transaction_date'], name='bank_transa_bank_ac_89ae9f_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['client_id'], name='bank_transa_client__d9d9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['case_id'], name='bank_transa_case_id_7c7fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['vendor_id'], name='bank_transa_vendor__92455e_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_date', 'transaction_type'], name='bank_transa_transac_a87669_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_number'], name='bank_transa_transac_a4828a_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['status', 'transaction_date'], name='bank_transa_status_a92de8_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['status'], name='bank_transa_status_b8b399_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['check_number'], name='bank_transa_check_n_eca858_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reference_number'], name='bank_transa_referen_cb533e_idx'),
        ),
    ]
