# Generated by Django 4.2.7 on 2025-11-26 08:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.IntegerField(default=0, help_text='Last case number assigned (CASE-XXXXXX format)')),
            ],
            options={
                'verbose_name': 'Case Number Counter',
                'verbose_name_plural': 'Case Number Counters',
                'db_table': 'case_number_counter',
            },
        ),
        migrations.CreateModel(
            name='ImportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('import_type', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Import')], max_length=20)),
                ('file_name', models.CharField(blank=True, help_text='Original filename for CSV imports', max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='in_progress', max_length=20)),
                ('total_records', models.IntegerField(default=0, help_text='Total records attempted')),
                ('successful_records', models.IntegerField(default=0, help_text='Successfully imported')),
                ('failed_records', models.IntegerField(default=0, help_text='Failed to import')),
                ('clients_created', models.IntegerField(default=0)),
                ('cases_created', models.IntegerField(default=0)),
                ('transactions_created', models.IntegerField(default=0)),
                ('vendors_created', models.IntegerField(default=0)),
                ('clients_skipped', models.IntegerField(default=0, help_text='Clients skipped (duplicates)')),
                ('cases_skipped', models.IntegerField(default=0, help_text='Cases skipped (duplicates)')),
                ('vendors_skipped', models.IntegerField(default=0, help_text='Vendors skipped (duplicates)')),
                ('rows_with_errors', models.IntegerField(default=0, help_text='Rows with null/invalid data')),
                ('expected_clients', models.IntegerField(default=0, help_text='Expected new clients from preview')),
                ('expected_cases', models.IntegerField(default=0, help_text='Expected new cases from preview')),
                ('expected_transactions', models.IntegerField(default=0, help_text='Expected new transactions from preview')),
                ('expected_vendors', models.IntegerField(default=0, help_text='Expected new vendors from preview')),
                ('total_clients_in_csv', models.IntegerField(default=0, help_text='Total client rows in CSV (including duplicates)')),
                ('total_cases_in_csv', models.IntegerField(default=0, help_text='Total case rows in CSV (including duplicates)')),
                ('total_transactions_in_csv', models.IntegerField(default=0, help_text='Total transaction rows in CSV')),
                ('total_vendors_in_csv', models.IntegerField(default=0, help_text='Total vendor rows in CSV (including duplicates)')),
                ('existing_clients', models.IntegerField(default=0, help_text='Clients already in system')),
                ('existing_cases', models.IntegerField(default=0, help_text='Cases already in system')),
                ('existing_vendors', models.IntegerField(default=0, help_text='Vendors already in system')),
                ('preview_data', models.TextField(blank=True, help_text='JSON data from preview validation')),
                ('preview_errors', models.TextField(blank=True, help_text='Validation errors found during preview')),
                ('error_log', models.TextField(blank=True, help_text='JSON or text log of errors')),
                ('imported_by', models.CharField(help_text='Username who performed import', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When import finished', null=True)),
            ],
            options={
                'verbose_name': 'Import Audit',
                'verbose_name_plural': 'Import Audits',
                'db_table': 'import_audit',
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(help_text='Full legal name of the law firm', max_length=200)),
                ('doing_business_as', models.CharField(blank=True, help_text='DBA name if different', max_length=200)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY'), ('DC', 'DC')], help_text='Two-letter state code', max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('principal_attorney', models.CharField(help_text='Managing partner or principal attorney', max_length=100)),
                ('attorney_bar_number', models.CharField(help_text='State bar registration number', max_length=20, validators=[django.core.validators.RegexValidator(message='Bar number must contain only letters, numbers, and hyphens', regex='^[A-Z0-9\\-]+$')])),
                ('attorney_state', models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY'), ('DC', 'DC')], help_text='State of bar admission', max_length=2)),
                ('trust_account_required', models.BooleanField(default=True)),
                ('iolta_compliant', models.BooleanField(default=False, help_text='Interest on Lawyer Trust Account compliance')),
                ('trust_account_certification_date', models.DateField(blank=True, help_text='Date of last trust account certification', null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Federal Tax ID (EIN)', max_length=20)),
                ('state_registration', models.CharField(blank=True, help_text='State business registration number', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Law Firm',
                'verbose_name_plural': 'Law Firm Information',
                'db_table': 'law_firm',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('managing_attorney', 'Managing Attorney'), ('staff_attorney', 'Staff Attorney'), ('paralegal', 'Paralegal'), ('bookkeeper', 'Bookkeeper'), ('system_admin', 'System Administrator')], default='paralegal', help_text='User role determines permissions', max_length=30)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID or bar number', max_length=50)),
                ('department', models.CharField(blank=True, help_text='Department or practice area', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='User can access the system')),
                ('can_approve_transactions', models.BooleanField(default=False, help_text='Can approve high-value transactions (≥ $10,000)')),
                ('can_reconcile', models.BooleanField(default=False, help_text='Can perform bank reconciliation')),
                ('can_print_checks', models.BooleanField(default=False, help_text='Can print checks (requires dual approval)')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can create/edit user accounts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Link to Django User account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings',
                'ordering': ['category', 'display_order', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('quickbooks', 'QuickBooks Import'), ('csv', 'CSV Import'), ('excel', 'Excel Import'), ('api', 'API Import')], max_length=50)),
                ('filename', models.CharField(blank=True, help_text='Original filename', max_length=255, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.IntegerField(blank=True, help_text='Total rows in import file', null=True)),
                ('clients_created', models.IntegerField(default=0, help_text='New clients created')),
                ('clients_existing', models.IntegerField(default=0, help_text='Existing clients found')),
                ('cases_created', models.IntegerField(default=0, help_text='New cases created')),
                ('transactions_created', models.IntegerField(default=0, help_text='New transactions created')),
                ('transactions_skipped', models.IntegerField(default=0, help_text='Transactions skipped (duplicates)')),
                ('errors', models.JSONField(blank=True, help_text='JSON array of error messages', null=True)),
                ('summary', models.JSONField(blank=True, help_text='JSON summary of import results', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who performed the import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'db_table': 'import_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_check_number', models.IntegerField(default=1001, help_text='Next check number to assign')),
                ('last_assigned_number', models.IntegerField(blank=True, help_text='Last check number that was assigned', null=True)),
                ('last_assigned_date', models.DateTimeField(blank=True, help_text='When the last check number was assigned', null=True)),
                ('bank_account', models.OneToOneField(help_text='Bank account for this check sequence', on_delete=django.db.models.deletion.CASCADE, related_name='check_sequence', to='bank_accounts.bankaccount')),
            ],
            options={
                'verbose_name': 'Check Sequence',
                'verbose_name_plural': 'Check Sequences',
                'db_table': 'check_sequences',
            },
        ),
    ]
